NAME = so_long

CC = gcc
CFLAGS = -Wall -Wextra -Werror

SRCS = so_long.c \
		accessibility_controls.c \
		exit_game.c \
		init_map.c \
		map_checker.c \
		read_map.c

OBJS = $(SRCS:.c=.o)

LIBFT_DIR = ./libs/libft
LIBFT = $(LIBFT_DIR)/libft.a
INCLUDES = -I. -I$(LIBFT_DIR)

all: $(NAME)

$(NAME): $(LIBFT) $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBFT) -o $(NAME)

$(LIBFT):
	make -C $(LIBFT_DIR)

clean:
	make -C $(LIBFT_DIR) clean
	rm -f $(OBJS)

fclean: clean
	make -C $(LIBFT_DIR) fclean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
